version: '3'
services:
  nginx:
    build: ./docker
    ports:
      - "80:80"  # Mapea el puerto 80 del host al puerto 80 del contenedor
    networks:
      - mynetwork  # Define una red para la comunicación interna entre contenedores

networks:
  mynetwork:
    driver: bridge  # Define una red interna para la comunicación entre contenedores
